adding hfip tests
NOAA-GSL/ufs-weather-model pull request #145
Opened 2022-06-30 02:35 UTC by shansun6

## Description

-- adding total 11 HFIP-related tests as shown in rt_hfip.conf;
-- GF and MYNN combined configuration (p8+GF+MYNN) is able to pass decomp, 2threads, debug and restart tests.

## Dependencies

- waiting on NOAA-GSL/fv3atm/pull/150, which contains the SDF that are needed in these tests.

2022-06-30 14:33 UTC, SamuelTrahanNOAA requested changes
In addition to these requested changes, you also need to run the full regression test suite for Intel and GNU, due to your change to the default_vars.sh

2022-06-30 14:33 UTC, SamuelTrahanNOAA commented on tests/default_vars.sh
> -export LHEATSTRG=.true.
Changing the default values may change the results of other tests. You need to run the full regression test suite for Intel and GNU to confirm results do not change.

2022-06-30 14:33 UTC, SamuelTrahanNOAA commented on tests/log_hera.intel/rt_001_control_p8_gf_mynn_hfip.log
> +
This file should not be in the repository.

2022-06-30 14:33 UTC, SamuelTrahanNOAA commented on tests/log_hera.intel/rt_002_control_decomp_p8_gf_mynn_hfip.log
> +
This file should not be in the repository.

2022-06-30 14:33 UTC, SamuelTrahanNOAA commented on tests/log_hera.intel/rt_003_control_2threads_p8_gf_mynn_hfip.log
> +
This file should not be in the repository.

2022-06-30 14:33 UTC, SamuelTrahanNOAA commented on tests/log_hera.intel/rt_004_control_restart_p8_gf_mynn_hfip.log
> +
This file should not be in the repository.

2022-06-30 14:44 UTC, hannahcbarnes approved these changes

2022-06-30 14:55 UTC, shansun6 commented
Thanks for your feedback. In order to avoid running full regression test
suite, how about leave default_vars.sh as is, and insert this line

export LHEATSTRG=.false.

in each of the 11 tests?

I will remove the rt*log.

Thanks for your prompt response.

Shan

On Thu, Jun 30, 2022 at 8:44 AM Hannah C Barnes ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-GSL/ufs-weather-model/pull/145#pullrequestreview-1025004957>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALORMVQ5BTE2FOAQWFE4SQ3VRWXFFANCNFSM52HXTYKA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-06-30 15:02 UTC, SamuelTrahanNOAA commented
Yes, that plan sounds fine.

2022-06-30 16:01 UTC, SamuelTrahanNOAA requested changes

2022-06-30 16:01 UTC, SamuelTrahanNOAA commented on tests/tests/control_p8
> -export LHEATSTRG=.true.
Why do you need to change the control_p8 variables? You should run the control_p8 test to make sure the results don't change.

2022-06-30 16:10 UTC, ShanSunNOAA commented
Good catch - I didn't mean to change this one.

Thanks,
Shan

On Thu, Jun 30, 2022 at 10:02 AM Samuel Trahan (NOAA contractor) <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In tests/tests/control_p8
> <https://github.com/NOAA-GSL/ufs-weather-model/pull/145#discussion_r911203869>
> :
>
> > @@ -91,7 +91,6 @@ export USE_MERRA2=.true.
>  export IAER=1011
>  export NSTF_NAME=2,1,0,0,0
>
> -export LHEATSTRG=.true.
>
> Why do you need to change the control_p8 variables? You should run the
> control_p8 test to make sure the results don't change.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-GSL/ufs-weather-model/pull/145#pullrequestreview-1025132378>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALORMVU7QQZEK5RYUYARQW3VRXAHFANCNFSM52HXTYKA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-06-30 16:11 UTC, SamuelTrahanNOAA requested changes

2022-06-30 16:11 UTC, SamuelTrahanNOAA commented on tests/rt_hfip.conf
> +###################################################################################################################################################################################
If you want these test to keep working after updates, they need to be in rt.conf and rt_gnu.conf.

2022-06-30 16:42 UTC, shansun6 commented
Good idea - done! Thanks,

Shan

On Thu, Jun 30, 2022 at 10:11 AM Samuel Trahan (NOAA contractor) <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In tests/rt_hfip.conf
> <https://github.com/NOAA-GSL/ufs-weather-model/pull/145#discussion_r911213186>
> :
>
> > @@ -0,0 +1,23 @@
> +###################################################################################################################################################################################
>
> If you want these test to keep working after updates, they need to be in
> rt.conf and rt_gnu.conf.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-GSL/ufs-weather-model/pull/145#pullrequestreview-1025148444>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALORMVXRSF2UZ77H64MVKS3VRXBKRANCNFSM52HXTYKA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-06-30 17:34 UTC, SamuelTrahanNOAA approved these changes

2022-06-30 22:26 UTC, SamuelTrahanNOAA requested changes
The ufs-weather-model PR does not point to the FV3 submodule PR https://github.com/NOAA-GSL/fv3atm/pull/150

2022-06-30 22:37 UTC, shansun6 commented
Done. Sorry for becoming rusty so soon.

Shan

On Thu, Jun 30, 2022 at 4:26 PM Samuel Trahan (NOAA contractor) <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> The ufs-weather-model PR does not point to the FV3 submodule PR
> NOAA-GSL/fv3atm#150 <https://github.com/NOAA-GSL/fv3atm/pull/150>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-GSL/ufs-weather-model/pull/145#pullrequestreview-1025550605>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALORMVV5SJEDWPD2MML2XA3VRYNJJANCNFSM52HXTYKA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-06-30 22:55 UTC, SamuelTrahanNOAA requested changes
I need to know that your new tests actually work in rt.conf and rt_gnu.conf. Right now, they won't because you edited the files incorrectly. Please generate baselines and run regression tests just for the five new tests in each of rt.conf and rt_gnu.conf to make sure you added them correctly.

1. Copy the relevant RUN and COMPILE lines from rt.conf and rt_gnu.conf to newtests.conf and newtests_gnu.conf
2. ./rt.sh -l newtests.conf -r -c
3. ./rt.sh -l newtests.conf -r -m
4. /usr/bin/env RT_COMPILER=gnu ./rt.sh -l newtests_gnu.conf -r -c
5. /usr/bin/env RT_COMPILER=gnu ./rt.sh -l newtests_gnu.conf -r -m

You may need to set other variables, as described in the instructions you made earlier.

2022-06-30 22:55 UTC, SamuelTrahanNOAA commented on tests/rt_gnu.conf
> +RUN     | control_debug_p8_gf_mynn_hfip                                                                                           |                |             |
This line should have "fv3" in it so it will generate a baseline. Also, you need to update the debug compile line to compile this suite.

2022-06-30 22:55 UTC, SamuelTrahanNOAA commented on tests/rt.conf
> +RUN     | control_debug_p8_gf_mynn_hfip                                                                                           |                                         |     |
This line should have "fv3" in it so it will generate a baseline.

2022-07-01 01:52 UTC, shansun6 commented
Thanks for your info. This fixed the missing baseline for the debug test
that I was puzzled about.

Shan

On Thu, Jun 30, 2022 at 4:56 PM Samuel Trahan (NOAA contractor) <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> I need to know that your new tests actually work in rt.conf and
> rt_gnu.conf. Right now, they won't because you edited the files
> incorrectly. Please generate baselines and run regression tests just for
> the five new tests in each of rt.conf and rt_gnu.conf to make sure you
> added them correctly.
>
>    1. Copy the relevant RUN and COMPILE lines from rt.conf and
>    rt_gnu.conf to newtests.conf and newtests_gnu.conf
>    2. ./rt.sh -l newtests.conf -r -c
>    3. ./rt.sh -l newtests.conf -r -m
>    4. /usr/bin/env RT_COMPILER=gnu ./rt.sh -l newtests_gnu.conf -r -c
>    5. /usr/bin/env RT_COMPILER=gnu ./rt.sh -l newtests_gnu.conf -r -m
>
> You may need to set other variables, as described in the instructions you
> made earlier.
> ------------------------------
>
> In tests/rt_gnu.conf
> <https://github.com/NOAA-GSL/ufs-weather-model/pull/145#discussion_r911496260>
> :
>
> > @@ -56,6 +60,7 @@ RUN     | control_thompson_progcld_thompson_debug
>  RUN     | control_ras_debug                                                                                                       |                | fv3         |
>  RUN     | control_stochy_debug                                                                                                    |                | fv3         |
>  RUN     | control_debug_p8                                                                                                        |                | fv3         |
> +RUN     | control_debug_p8_gf_mynn_hfip                                                                                           |                |             |
>
> This line should have "fv3" in it so it will generate a baseline. Also,
> you need to update the debug compile line to compile this suite.
> ------------------------------
>
> In tests/rt.conf
> <https://github.com/NOAA-GSL/ufs-weather-model/pull/145#discussion_r911496433>
> :
>
> > @@ -139,6 +144,7 @@ RUN     | rap_unified_ugwp_debug
>  RUN     | rap_lndp_debug                                                                                                          |                                         | fv3 |
>  RUN     | rap_flake_debug                                                                                                         |                                         | fv3 |
>  RUN     | rap_progcld_thompson_debug                                                                                              |                                         | fv3 |
> +RUN     | control_debug_p8_gf_mynn_hfip                                                                                           |                                         |     |
>
> This line should have "fv3" in it so it will generate a baseline.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-GSL/ufs-weather-model/pull/145#pullrequestreview-1025562124>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALORMVUILFAWENJE45CNFGTVRYQYPANCNFSM52HXTYKA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-07-01 12:05 UTC, joeolson42 approved these changes

2022-07-07 12:30 UTC, SamuelTrahanNOAA approved these changes

2022-07-07 17:14 UTC, merged