updates for RRFS baseline E
NOAA-GSL/ufs-weather-model pull request #151
Opened 2022-10-10 16:41 UTC by hu5970

Updates for baseline E:
1).   Add code from EmC (Jun Wang) for fast read restart files.
2).  update points to submodules.

This PR depends on:
https://github.com/NOAA-GSL/ccpp-physics/pull/164
https://github.com/NOAA-GSL/GFDL_atmos_cubed_sphere/pull/13
https://github.com/NOAA-GSL/fv3atm/pull/157

2022-10-11 14:23 UTC, hannahcbarnes approved these changes

2022-10-11 14:41 UTC, joeolson42 approved these changes

2022-10-11 14:42 UTC, haiqinli approved these changes

2022-10-11 15:52 UTC, SamuelTrahanNOAA requested changes
Smoke debug tests fail with a floating-point exception at line 5353 of module_bl_mynn.F90.

2022-10-11 15:59 UTC, mdtoyNOAA approved these changes

2022-10-11 16:26 UTC, tanyasmirnova approved these changes

2022-10-11 17:07 UTC, zhanglikate approved these changes

2022-10-12 21:47 UTC, tanyasmirnova approved these changes

2022-10-13 15:08 UTC, SamuelTrahanNOAA approved these changes

2022-10-13 15:08 UTC, merged