Update of subgrid-scale cloud physics for MYNN/GF
NOAA-GSL/ufs-weather-model pull request #2
Opened 2019-12-13 22:20 UTC by climbfuji

This PR updates the submodule pointer for FV3 for the code changes described in https://github.com/NOAA-GSD/fv3atm/pull/3 and https://github.com/NOAA-GSD/ccpp-physics/pull/2. 

Associated PRs:
https://github.com/NOAA-GSD/ccpp-physics/pull/2
https://github.com/NOAA-GSD/fv3atm/pull/3
MISS

See https://github.com/NOAA-GSD/fv3atm/pull/3 for regression testing information.

2019-12-15 14:11 UTC, DomHeinzeller requested changes
This PR cannot be merged (see https://github.com/NOAA-GSD/fv3atm/pull/3 for details).

2019-12-20 00:23 UTC, DomHeinzeller approved these changes

2019-12-20 16:53 UTC, DomHeinzeller commented
@tanyasmirnova @haiqinli Per request from @joeolson42 I put these PRs on hold. Please base your work on the latest gsd/develop and pull changes from these PRs in as needed so that I do not have to replicate the work done thus far. Thank you!

2020-03-13 13:28 UTC, DomHeinzeller commented
@haiqinli @tanyasmirnova @joeolson42 @hannahcbarnes I believe this PR has been superseded by #11 which I just merged? Please confirm. Thanks!

2020-03-13 16:25 UTC, climbfuji commented
Superseded by https://github.com/NOAA-GSD/ufs-weather-model/pull/11

2020-03-13 16:25 UTC, closed without merging